DROP TABLE IF EXISTS `semanticweb`.`thistorictitle`;
DROP TABLE IF EXISTS `semanticweb`.`tcoach`;
DROP TABLE IF EXISTS `semanticweb`.`tstadium`;
DROP TABLE IF EXISTS `semanticweb`.`tchiefs`;
DROP TABLE IF EXISTS `semanticweb`.`ttitle`;
CREATE TABLE `semanticweb`.`tcoach` ( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(255) NOT NULL , `initial_date` DATE , `final_date` DATE , `semantic` VARCHAR(255) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `semanticweb`.`tstadium` ( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(255) NOT NULL , `initial_date` DATE , `final_date` DATE , `semantic` VARCHAR(255) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `semanticweb`.`tchiefs` ( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(255) NOT NULL , `initial_date` DATE , `final_date` DATE , `semantic` VARCHAR(255) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `semanticweb`.`ttitle` ( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(255) NOT NULL , `semantic` VARCHAR(255) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `semanticweb`.`thistorictitle` ( `id` INT NOT NULL AUTO_INCREMENT, `date` DATE NOT NULL,`id_title` INT NOT NULL , PRIMARY KEY (`id`), CONSTRAINT FK_COACHTITLE_TITLE FOREIGN KEY (id_title) REFERENCES ttitle(id) ) ENGINE = InnoDB;
INSERT INTO `semanticweb`.`ttitle`(`name`, `semantic`) VALUES ('European Cup', 'https://www.uefa.com/uefachampionsleague');
INSERT INTO `semanticweb`.`ttitle`(`name`, `semantic`) VALUES ('Bundesliga', 'https://www.bundesliga.com/en/bundesliga');
INSERT INTO `semanticweb`.`ttitle`(`name`, `semantic`) VALUES ('DFB Pokal', 'https://www.dfb.de/en/dfb-pokal/mens-dfb-pokal/');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (1, '1974-05-17');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (1, '1975-05-28');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (1, '1976-05-12');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (1, '2001-05-23');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (1, '2013-05-25');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (1, '2020-08-23');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1932-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1969-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1972-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1973-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1974-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1980-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1981-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1985-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1986-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1987-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1989-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1990-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1994-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1997-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '1999-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2000-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2001-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2003-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2005-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2006-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2008-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2010-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2013-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2014-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2015-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2016-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2017-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2018-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2019-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (2, '2020-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '1957-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '1966-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '1967-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '1969-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '1971-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '1982-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '1984-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '1986-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '1998-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '2000-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '2003-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '2005-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '2006-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '2008-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '2010-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '2013-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '2014-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '2016-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '2019-06-01');
INSERT INTO `semanticweb`.`thistorictitle`(`id_title`, `date`) VALUES (3, '2020-06-01');